(define(problem mctf-problem)
(:domain mctf)
(:objects b1 - blue b2 - red b3 - red r1 - red r2 - red r3 - red )
(:init 	(= (brow b1)  4)
	(= (bcol b1)  8)
	(= (rrow b2)  2)
	(= (rcol b2)  12)
	(= (rrow b3)  6)
	(= (rcol b3)  12)
	(= (rrow r1)  4)
	(= (rcol r1)  2)
	(= (rrow r2)  3)
	(= (rcol r2)  10)
	(= (rrow r3)  5)
	(= (rcol r3)  12)
	(= (rbrow)  4)
	(= (rbcol)  2)
	(= (bbrow)  4)
	(= (bbcol)  14)
	(red_flag_at_red_base)
)
(:goal (and  (>= (bcol b1)  9)  (blue_has_flag b1)  (not (blue_collide b1) ) ))
(:metric minimize(total-time))
)
