(define(problem cartpole_prob)
(:domain cartpole-initial-bhaskara)
(:objects dummy_obj - dummy )
(:init 	(= (m_cart)  1.0)
	(= (friction_cart)  0.0)
	(= (l_pole)  0.5)
	(= (m_pole)  0.1)
	(= (friction_pole)  0.0)
	(= (force_mag)  10.0)
	(= (inertia)  1.0)
	(= (elapsed_time)  0.0)
	(= (gravity)  9.81)
	(= (time_limit)  1.5)
	(= (angle_limit)  0.2)
	(= (x_limit)  2.4)
	(ready)
	(cart_available)
	(= (x)  0.0)
	(= (x_dot)  0.0)
	(= (theta)  0.0)
	(= (theta_dot)  0.0)
	(= (F)  10.0)
	(= (x_ddot)  0.0)
	(= (theta_ddot)  0.0)
)
(:goal (and  (not (total_failure) )  (= (elapsed_time)  (time_limit) ) ))
(:metric minimize(total-time))
)
